version: '3'

services:
  # api:
  #   build: .
  #   env_file:
  #     - .env
  #   ports:
  #     - 8000:8000
  #   restart: on-failure
  #   depends_on:
  #     - db

  db:
    image: postgres:15.1-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_TABLE}
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local